# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79325dfeb44ff0adc8dc9ff1981ab9290f351655039291006cdab024e883444e03896643bea2a024b55b4ea11eea4c3d4611a10ca83da419b57a1869726962a6

test:
  secret_key_base: 72ec0e63f5d52491dfd772598ab9a46ec3a4291ef948900939c3d977be6354dc9636074bee56f40dbaadbb398cdb759a6fd834b0ef559ab2680883bcf10eb9b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
